### ISSUE TITLE
Cant install via composer

### ISSUE THREAD

**Issue by gut8er** [Josef-A-Puckl/OXID_Cookbook_Autosuggestion#1]
Problem 1
    - The requested package josef-a-puckl/ocb_autosuggest could not be found in any version, there may be a typo in the package name.

Tried diffrent solutions to fix this. But it still dont work.

**Comment by gut8er** [comment]
I

**Comment by Josef-A-Puckl** [comment]
> there may be a typo in the package name

That's exactly how it is.
